### ISSUE TITLE
Migrate to graphql-upload

### ISSUE THREAD

**Issue by cosmicdreams** [elmsln/hax-desktop-app#12]
When installing this via the build script I get the following message:
npm WARN deprecated apollo-upload-server@7.1.0: Please migrate to https://npm.im/graphql-upload (see https://git.io/fADhl).

Doing so will probably involve making sure there are no regressions so I'll create a ticket for that.

**Comment by btopro** [comment]
I mean this project needs completely gutted to work off of the haxcms series of tags (as is planned tho I haven't written it down before). HAXCMS tags are highly abstracted away from the code base it sits within so whatever method of netting the fastest "backend" that sits on a desktop (or server for node based deploys of haxcms in that case) is fine with me.
